/usr/bin/apxs
/usr/include/apache2
/usr/share/apache2/build/*.sh
/usr/share/apache2/build/*.mk
debian/debhelper/apache2.pm		/usr/share/perl5/Debian/Debhelper/Sequence/
debian/debhelper/dh_apache2		/usr/bin
debian/debhelper/postinst-apache2	/usr/share/debhelper/autoscripts/
debian/debhelper/postrm-apache2		/usr/share/debhelper/autoscripts/
debian/debhelper/prerm-apache2		/usr/share/debhelper/autoscripts/
