name: "Debian"

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build (Push)"
    steps:
      - run: echo "PKG_NAME=$( echo '${{ github.repository }}' | awk -F 'debian-' '{print $2}' )" >> $GITHUB_ENV
        shell: bash
      - run: echo "PKG_OS=$( echo '${{ github.repository }}' | awk -F '-' '{print $1}' )" >> $GITHUB_ENV
        shell: bash
      - uses: ghastore/${{ github.repository_owner }}-${{ env.PKG_OS }}-build@main
        with:
          git_repo_src: "https://github.com/${{ github.repository }}.git"
          git_repo_dst: "https://github.com/${{ github.repository_owner }}-${{ env.PKG_OS }}/${{ env.PKG_NAME }}.git"
          git_user: "${{ secrets.BOT_GITHUB_NAME }}"
          git_email: "${{ secrets.BOT_GITHUB_EMAIL }}"
          git_token: "${{ secrets.BOT_GITHUB_TOKEN }}"
          obs_user: "${{ secrets.OBS_USER }}"
          obs_password: "${{ secrets.OBS_PASSWORD }}"
          obs_token: "${{ secrets.OBS_TOKEN }}"
          obs_project: "home:${{ github.repository_owner }}:${{ env.PKG_OS }}"
          obs_package: "${{ env.PKG_NAME }}"
