name: "Debian"

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build (Push)"
    steps:
      - run: echo "PKG_OS=$( echo '${{ github.repository }}' | awk -F '-' '{print $1}' )" >> $GITHUB_ENV
        shell: bash
      - run: echo "PKG_NAME=$( echo '${{ github.repository }}' | awk -F 'debian-' '{print $2}' )" >> $GITHUB_ENV
        shell: bash
      - run: echo "${{ env.PKG_OS }} / ${{ env.PKG_NAME }}"
        shell: bash
